language: python
python:
  - "3.5"
# command to install dependencies
# install: "pip install -r requirements.txt"
install: "pip install tox"

# command to run tests
script: tox

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

